-- CreatING MOVIES DATABASE
CREATE DATABASE IF NOT EXISTS MOVIES;

CREATE DATABASE SONGS;


-- Selecting database
-- syntax: USE DATABASENAME;
USE MOVIES;

-- REMOVE SONGS DATABASE 
-- SYNTAX: DROP DATABASE databasename;
DROP DATABASE IF EXISTS SONGS;

USE MOVIES;
CREATE TABLE IF NOT EXISTS TELUGU_MOVIES(
ID INT,
 MOVIENAME VARCHAR(30), 
 DIRECTOR VARCHAR(20), 
 DURATION INT
);
-- CHECK TABLE DESCRIPTION
-- SYNTAX:DESCRIBE TABLENAME;
DESCRIBE TELUGU_MOVIES;