-- CREAT DATABASE SCHOOL
CREATE DATABASE SCHOOL;
DROP DATABASE IF EXISTS SCHOOL;
USE SCHOOL;

CREATE TABLE STUDENTS (
    STUDENT_INT INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    GENDER VARCHAR(10),
    CLASS INT
);

DESCRIBE STUDENTS;


CREATE TABLE MARKS (
    STD_ID INT,
    SUBJECT1 tinyint,
    SUBJECT2 tinyint,
    SUBJECT3 tinyint,
    PERCENTAGE DECIMAL(4,2),
    FOREIGN KEY (STD_ID) REFERENCES STUDENTS(STUDENT_INT)
);

-- ALTER COMMAND OPERATIONS
-- ADD NEW AGE COLUMN
-- SYNTAX: ALTER TABLE TableName ADD COLUMN COLNAME DATATYPE [CONSTRAIN]

ALTER TABLE STUDENTS ADD AGE TINYINT CHECK(AGE > 5);


ALTER TABLE STUDENTS MODIFY COLUMN AGE TINYINT;

ALTER TABLE STUDENTS ADD CONSTRAINT chk_age CHECK (AGE > 5);
ALTER TABLE STUDENTS ADD DOB DATE;

ALTER TABLE STUDENTS ADD column LOCATION VARCHAR(50), ADD column ADDRESS VARCHAR(30);
DESCRIBE STUDENTS;


-- delete COLUMNS
-- SYNTAX: ALTER TABLE TABLENAME DROP COLUMN COLNAME;
-- DELETE LOCATION AND ADDRESS COLUMNS
ALTER TABLE STUDENTS DROP COLUMN LOCATION, DROP COLUMN ADDRESS;


-- CHANGE ID COLUMN NAME TO STDID
-- SYNTAX: ALTETR TABLE TABLENAME RENAME COLUMNNAME OLD_COL_NAME TO NEW_COL_NAME;

ALTER TABLE STUDENTS RENAME COLUMN STUDENT_INT TO STDID;

DESCRIBE STUDENTS;

-- CAHNGE GENDER COLUMN DATATYPE
-- SYNTAX: ALTER TABLE TABLENAME MODIEY COLUMN COLNAME DATATYPE [CONSTRAIN]
ALTER TABLE STUDENTS MODIFY COLUMN GENDER ENUM('MALE','FEMALE');
DESCRIBE STUDENTS;

-- CONVERT CLASS DATATYPE INTO TINYINT
ALTER TABLE STUDENTS MODIFY COLUMN CLASS TINYINT unsigned; 
DESC STUDENTS;

-- update CLASS AS NOT NULL
ALTER TABLE STUDENTS MODIFY COLUMN CLASS TINYINT unsigned NOT NULL;

-- DROP STUDENTS TABLE 
DROP TABLE STUDENTS;

DESC STUDENTS;


-- INSERT RECORD INTO STUDENTS TABLES (1ST WAY)
INSERT INTO STUDENTS VALUES(101,"MANUSHA","FEMALE",6,11, "21-08-03");
# INSERT INTO STUDENTS VALUES(101,"MANUSHA","FEMALE",11, "21-08-03");


-- INSERT RECORD (2ND WAY)
INSERT INTO STUDENTS(NAME, GENDER, CLASS, AGE, DOB)
values("HARI","MALE",7,12, "01-02-14"),
		("RIYA","FEMALE",8,13, "18-12-15");


-- FETCH TABLE DATA 
SELECT * FROM STUDENTS;
DELETE FROM STUDENTS
WHERE STUDENT_INT IN (110, 111);

SELECT * FROM STUDENTS;

DELETE FROM STUDENTS
WHERE STUDENT_INT IN (112, 113);

SELECT * FROM STUDENTS;


--  marks table 
CREATE TABLE MARKS (
    STD_ID INT,
    SUBJECT1 TINYINT,
    SUBJECT2 TINYINT,
    SUBJECT3 TINYINT,
    PERCENTAGE DECIMAL(4,2),
    FOREIGN KEY (STD_ID) REFERENCES STUDENTS(STDID)
);
DESC MARKS;

-- INSERT RECORDS INTO MARKS

INSERT INTO MARKS
(STD_ID, SUBJECT1, SUBJECT2, SUBJECT3, PERCENTAGE)
VALUES
(101, 95, 93, 94, 94.00),
(102, 85, 86, 87, 86.00);

SET SQL_SAFE_UPDATES = 0;

DELETE FROM MARKS;

SET SQL_SAFE_UPDATES = 1;

INSERT INTO MARKS
(STD_ID, SUBJECT1, SUBJECT2, SUBJECT3, PERCENTAGE)
VALUES
(101, 95, 93, 94, 94.00),
(102, 85, 86, 87, 86.00);

SELECT * FROM MARKS;


-- UPDATE 5 MARKS FOR 101 STUDENT FOR SUBJECT1 
SELECT * FROM MARKS WHERE STD_ID = 101;

UPDATE MARKS SET SUBJECT1 = SUBJECT1 + 5
WHERE STD_ID = 101;


-- UPDATE 5 MARKS FOR 101 STUDENT FOR SUBJECT1 AND SUBJECT2
SELECT * FROM MARKS WHERE STD_ID = 102;

UPDATE MARKS SET SUBJECT1 = SUBJECT1 + 5, 
SUBJECT2 = SUBJECT2 + 5
WHERE STD_ID = 102;


-- UPDATE PERCENTAGE COLUMN AS DERIVED COLUMN
ALTER TABLE MARKS MODIFY COLUMN PERCENTAGE FLOAT(4,2) 
						GENERATED ALWAYS AS ((SUBJECT1 + SUBJECT2 + SUBJECT3) / 3) STORED;
SELECT * FROM MARKS;


-- ADD TOTAL_MARKS COLUMN TO MARKS TABLE
ALTER TABLE MARKS ADD COLUMN TOTAL_MARKS INT
					GENERATED ALWAYS AS (SUBJECT1 + SUBJECT2 + SUBJECT3) STORED AFTER SUBJECT3;
                    
SELECT * FROM MARKS;

SELECT * FROM STUDENTS;


INSERT INTO STUDENTS(NAME, GENDER, CLASS, AGE, DOB)
VALUES
("ARJUN", "MALE", 7, 12, "15-03-14"),
("SNEHA", "FEMALE", 8, 13, "22-05-13"),
("RAHUL", "MALE", 9, 14, "10-07-12"),
("PRIYA", "FEMALE", 7, 12, "28-09-14"),
("KIRAN", "MALE", 8, 13, "05-11-13"),
("ANANYA", "FEMALE", 9, 14, "19-01-12"),
("ROHAN", "MALE", 7, 12, "30-06-14");
SELECT * FROM STUDENTS;

SELECT STD_ID, NAME FROM STUDENTS;


-- CREATE BACKUP TABLE FOR STUDENTS
 
CREATE TABLE STUDENTS_BACKUP_TABLE AS
SELECT * FROM STUDENTS;

SELECT * FROM STUDENTS_BACKUP_TABLE;
DESC STUDENTS_BACKUP_TABLE;
DESC STUDENTS;

-- CREATE A STUDENT INFO TABLE (ID) (NAME) (CLASS)



CREATE TABLE STUDENTS_INFO AS
SELECT STDID, NAME AS STDNAME , CLASS FROM STUDENTS;

SELECT * FROM STUDENTS_INFO;


-- CREAT TBALE 6TH CLASS STUDENT DATA
						-- WHERE CLASS :- USED TO FILETER DATA
CREATE TABLE CLASS6 AS
SELECT STDID, NAME, CLASS FROM STUDENTS
WHERE CLASS = 6;

SELECT * FROM CLASS6;

-- CREAT TBALE 7TH CLASS STUDENT DATA

CREATE TABLE CLASS7 AS
SELECT STDID, NAME FROM STUDENTS
WHERE CLASS = 7;
SELECT * FROM CLASS7;

-- CREATE NEW TBALE STRUCUTE FROM AN EXISITING TBALE STRUCTURE
CREATE TABLE STUDENTS1 AS 
SELECT  * FROM STUDENTS
WHERE 1 = 0;

SELECT * FROM STUDENTS1;

-- HERE WE USE LIKE OPERATOR TO COPY STUCTURE

CREATE TABLE STUDENTS2 LIKE STUDENTS;
SELECT * FROM STUDENTS2;

-- HERE WE ADD NEW VALUE AND CHECK IF IT UPDATES IN BACK_UP VALUE
INSERT INTO STUDENTS(NAME, GENDER, CLASS, AGE, DOB)
VALUES
("SHRAVANI", "FEMALE", 6, 10, "14-07-12");
SELECT * FROM STUDENTS;
SELECT * FROM CLASS6;

-- UPDATE STUDENT TABLE
UPDATE STUDENTS
SET AGE = 13
WHERE STDID = 102;

SELECT * FROM STUDENTS;
SELECT * FROM STUDENTS_BACKUP_TABLE;