CREATE database tips_analysis;
USE tips_analysis;
select*from tips;
desc tips;

-- change SEX column name to GENDER
ALTER TABLE tips RENAME COLUMN SEX to GENDER;
SELECT * FROM tips;

-- 1. GET FEMALE RECORDS
SELECT * FROM tips WHERE sex = 'Female';

-- 2.FIND MALE RECORDS
SELECT * FROM tips WHERE sex = 'male';

-- 3. FIND DINNER TIME FEMALE RECORDS
SELECT * FROM tips WHERE sex = 'Female'and Time= 'DINNER';

-- 4.FIND THE SIZE 2 RECORDS
 SELECT *FROM TIPS WHERE SIZE =2;
 
-- 5. FIND MALE SMOKER RECORDS
 SELECT *FROM TIPS WHERE SEX= 'MALE' AND SMOKER='YES';
 
-- 6. GET THE NON-SMOKER FEMALE RECORDS
SELECT *FROM TIPS WHERE SEX= 'FEMALE' AND SMOKER='NO';

-- 7. GET THE DINNER TIME MALE RECORDS
SELECT * FROM tips WHERE sex = 'male'and Time= 'DINNER';

-- 8. GET THE FEMALE RECORDS IN DESCENDING ORDER AS PER THE TOTAL_BILL
SELECT * FROM tips WHERE sex = 'Female' ORDER BY TOTAL_BILL DESC;

-- 9. GET THE TOP 5 MALE TOTAL_BILLS
SELECT * FROM tips WHERE sex = 'male' ORDER BY TOTAL_BILL DESC LIMIT 5;

-- 10. GET BOTH SIZE 2 AND 3 RECORDS
SELECT *FROM tips WHERE size = 2 OR size = 3;

-- 11. GET THE RECORDS WHOSE TOTAL BILL IN THE RANGE OF 10 TO 20
SELECT * FROM TIPS WHERE TOTAL_BILL BETWEEN 10 AND 20;
SELECT * FROM TIPS WHERE TOTAL_BILL >=10 AND TOTAL_BILL <=20;
-- 12. GET SIZE 2,3 AND 4 RECORDS
SELECT *FROM TIPS where size = 2 or size=3 or size=4;
SELECT *FROM TIPS where size IN (2,3,4);

-- 13.SECOND HIGHEST TOTAL BILL RECORD
SELECT*FROM TIPS ORDER BY TOTAL_BILL DESC
LIMIT 1 OFFSET 1;

SELECT*FROM TIPS ORDER BY TOTAL_BILL DESC
LIMIT 1 OFFSET 2;

SELECT*FROM TIPS ORDER BY TOTAL_BILL DESC
LIMIT 2 OFFSET 1;

-- 14. RETURN TOTAL RECORDS IN TIPS TABLE
SELECT COUNT(*) FROM TIPS;

-- 15. RETURN TOTAL MALE SMOKER COUNT
SELECT COUNT(*) FROM TIPS WHERE SEX='MALE' AND SMOKER='YES';

-- 16. RETURN TOTAL TIPS
SELECT SUM(TIP) FROM TIPS;

-- 17. RETURN FEMALE NON SMOKER COUNT
SELECT COUNT(*) FROM TIPS WHERE  SEX='FEMALE' AND SMOKER='NO';

-- 18. RETURN MINIMUM AND MAXIMUM TAOTAL BILL
SELECT MIN(TOTAL_BILL), MAX(TOTAL_BILL) FROM TIPS;

SELECT SEX, SMOKER, COUNT(*) FROM TIPS WHERE SEX= 'FEMALE' AND SMOKER='NO';

select*from tips;

-- GROUP BY QUERIES
-- 19. GET THE GENDER COLUMN UNIQUE VALUES
SELECT SEX FROM TIPS GROUP BY SEX;

SELECT DISTINCT SEX FROM TIPS;

-- 20. GET THE DINNER TIME RECORDS COUNT
SELECT COUNT(*) FROM TIPS  WHERE TIME = 'DINNER';

-- 21. GET THE TOTAL RECORDS COUNT AS PER THE GENDER COLUMN
SELECT SEX, COUNT(*) FROM TIPS GROUP BY SEX;

-- 22. GET THE SMOKER AND NON- SMOKER COUNT
SELECT SMOKER,COUNT(*) FROM TIPS GROUP BY SMOKER;

SELECT SMOKER,COUNT(*) AS TOTAL_COUNT FROM TIPS GROUP BY SMOKER;

-- 23. GET THE SUNDAY TOTAL RECORDS AS PER THE GENDER
SELECT SEX,COUNT(*) FROM TIPS WHERE DAY= 'SUN' GROUP BY SEX;

SELECT DAY,SEX,COUNT(*) FROM TIPS WHERE DAY= 'SUN' GROUP BY SEX;

-- 24. GET THE SIZE 2'S TOTAL COUNT AS PER THE GENDER
SELECT SEX, COUNT(*) FROM TIPS WHERE SIZE=2 GROUP BY SEX;

-- 25. GET THE EACH SIZE COUNT IN DESCENDING ORDER
SELECT SIZE, COUNT(*) FROM TIPS GROUP BY SIZE DESC;

SELECT SIZE, COUNT(*) AS TOTAL_COUNT FROM TIPS GROUP BY SIZE ORDER BY TOTAL_COUNT DESC;



-- 26. GET THE SIZE 2,3 AND 4 SMOKER AND NON SMOKER COUNT
SELECT SMOKER,COUNT(*) FROM TIPS WHERE SIZE IN (2,3,4) GROUP BY SMOKER ;

-- 27. GET THE EACH SIZE COUNT AS PER THE GENDER 
SELECT SIZE,SEX, COUNT(*) FROM TIPS GROUP BY SIZE,SEX;

SELECT SIZE,SEX, COUNT(*) AS TOTAL_COUNT FROM TIPS GROUP BY SIZE,SEX ORDER BY SIZE DESC;

SELECT SIZE,SEX, COUNT(*) AS TOTAL_COUNT FROM TIPS GROUP BY SIZE,SEX ORDER BY SIZE ASC, TOTAL_COUNT DESC;

-- 28. FIND THE EACH SIZE MAXIMUM AND MINIMUM TOTAL_BILL
SELECT SIZE, MIN(TOTAL_BILL), MAX(TOTAL_BILL) FROM TIPS GROUP BY SIZE;

-- 29. FIND THE MALE TOTAL RECORDS AS PER THE DAY IN DESCENDING ORDER
SELECT DAY, COUNT(*) FROM TIPS WHERE SEX='MALE' GROUP BY DAY DESC;

SELECT DAY, COUNT(*) AS TOTAL_COUNT FROM TIPS WHERE SEX='MALE' GROUP BY DAY ORDER BY TOTAL_COUNT  DESC;

-- 30. FIND TOTAL RECORDS AS PER THE SIZE

SELECT SIZE, COUNT(*) AS TOTAL_COUNT FROM TIPS  GROUP BY SIZE;

-- 31. RETURN THE SIZE WHICH ONE TOTAL COUNT IS MORETHAN 50
SELECT SIZE, COUNT(*) AS TOTAL_COUNT FROM TIPS GROUP BY SIZE  HAVING TOTAL_COUNT > 50;

-- 32. RETURN THE SIZE WHICH ONE TOTAL COUNT IS MORETHAN 30
SELECT SIZE, COUNT(*) AS TOTAL_COUNT FROM TIPS GROUP BY SIZE  HAVING COUNT(*) > 30;

-- GET THE EACH SIZE GENDER COUNT WHICH IS MORE THAN 20
SELECT SIZE,SEX, COUNT(*) FROM TIPS GROUP BY SIZE,SEX HAVING COUNT(*)>20;

-- 33. GET THE SIZES WHICH IS MAXIMUM TOTAL_BILL AND MINIMUM TOTAL_BILL DIFFERENCE IS LESSERTHAN 10

SELECT SIZE, MAX(TOTAL_BILL),MIN(TOTAL_BILL) FROM tips GROUP BY SIZE HAVING MAX(TOTAL_BILL)- MIN(TOTAL_BILL)<10;

SELECT SIZE, MAX(TOTAL_BILL),MIN(TOTAL_BILL) FROM tips GROUP BY SIZE HAVING MAX(TOTAL_BILL)- MIN(TOTAL_BILL)<20;

SELECT SIZE, MAX(TOTAL_BILL),MIN(TOTAL_BILL) FROM tips GROUP BY SIZE HAVING MAX(TOTAL_BILL)- MIN(TOTAL_BILL)<30;

SELECT SIZE, MAX(TOTAL_BILL),MIN(TOTAL_BILL),( MAX(TOTAL_BILL)- MIN(TOTAL_BILL)) 
FROM tips GROUP BY SIZE HAVING MAX(TOTAL_BILL)- MIN(TOTAL_BILL)<30;